//
//  PageRouter.swift
//  PlainText2AttributedString
//
//  Created by Krzysztof Pawski on 15/02/16.
//  Copyright (c) 2016 Krzysztof Pawski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PageRouterInput {
  func navigateToTagDetailScene()
}

final class PageRouter {
  weak var viewController: PageViewController!
  
  // MARK: Navigation
  
  func navigateToTagDetailScene() {
  }
  
  func navigateToChaptersListScene() {
  }
  
  func navigateToPageScene() {
  }
  
  func navigateToResourceElementsScene() {
  }
  
  // MARK: Communication
  
  func passDataToNextScene(segue: UIStoryboardSegue) {
    guard let segueId = segue.identifier else {
      return
    }
    
    switch segueId {
      case "showTagDetail":
        passDataToTagDetailScene(segue)
        break
      case "showChaptersList":
        passDataToChaptersListScene(segue)
        break
      case "showResourceElements":
        passDataToResourceElementsScene(segue)
        break
      case "showWebView":
        passDataToWebView(segue)
        break
      default:
        break
    }
  }
  
  func passDataToTagDetailScene(segue: UIStoryboardSegue) {
  }
  
  func passDataToChaptersListScene(segue: UIStoryboardSegue) {
  }
  
  func passDataToPageScene(pageViewController: PageViewController) {
  }
  
  func passDataToResourceElementsScene(segue: UIStoryboardSegue) {  }
  
  func passDataToWebView(segue: UIStoryboardSegue) {
  }
}
