//
//  PagePresenter.swift
//  PlainText2AttributedString
//
//  Created by Krzysztof Pawski on 15/02/16.
//  Copyright (c) 2016 Krzysztof Pawski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PagePresenterInput {
  func presentFetchedPages(response: PageScene.FetchPages.Response)
}

protocol PagePresenterOutput: class {
  func displayFetchedPages(viewModel: PageScene.FetchPages.ViewModel)
}

final class PagePresenter: PagePresenterInput {
  weak var output: PagePresenterOutput!
  
  // MARK: Presentation logic
  
  func presentFetchedPages(response: PageScene.FetchPages.Response) {
    var pageModels: [PageScene.FetchPages.ViewModel.PageViewModel] = []
    for p in response.pages {
      let parser = AttributesParser(content: p.content, textColor: UIColor.blackColor())
      let page = PageScene.FetchPages.ViewModel.PageViewModel(id: p.id, content: parser.processedContent())
      pageModels.append(page)
    }
    
    let viewModel = PageScene.FetchPages.ViewModel(pageModels: pageModels)
    output.displayFetchedPages(viewModel)
  }
}
