//
//  PageModels.swift
//  PlainText2AttributedString
//
//  Created by Krzysztof Pawski on 15/02/16.
//  Copyright (c) 2016 Krzysztof Pawski. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: FetchPages

struct PageScene {
  
  struct FetchPages {
    
    struct Request {
    }
    
    struct Response {
      var pages: [Page]!
    }
    
    struct ViewModel {
      struct PageViewModel {
        var id: UInt
        var content: NSAttributedString?
      }
      var pageModels: [PageViewModel]
    }
  }
}

